sonar.projectKey=dezign8
sonar.projectName=dezign8
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,.astro/**,dist/**
sonar.token=sqp_836ca14add1a65ffcdf87f86097b6a5aa1d33705